name: Update APNIC IP Lists

on:
  schedule:
    - cron: '1 4 * * *'
  workflow_dispatch:

jobs:
  update-lists:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Delete all files in the output directory
        run: |
          rm -rf routeros_lists/*
          rm -rf cidr_lists/*

      - name: Download APNIC data
        run: |
          wget -O /tmp/delegated-latest http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest
          
      - name: Process APNIC data
        run: |
          python3 generate_routeros_lists.py
      - name: Download RIPE data
        run: |
          wget -O /tmp/delegated-latest https://ftp.ripe.net/ripe/stats/delegated-ripencc-latest
          
      - name: Process RIPE data
        run: |
          python3 generate_routeros_lists.py
      - name: Download AFRINIC data
        run: |
          wget -O /tmp/delegated-latest https://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-latest
          
      - name: Process AFRINIC data
        run: |
          python3 generate_routeros_lists.py
      - name: Download ARIN data
        run: |
          wget -O /tmp/delegated-latest https://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest
          
      - name: Process ARIN data
        run: |
          python3 generate_routeros_lists.py
      - name: Download LACNIC data
        run: |
          wget -O /tmp/delegated-latest https://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-latest
          
      - name: Process LACNIC data
        run: |
          python3 generate_routeros_lists.py
          
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update at $(date +'%Y-%m-%d %H:%M:%S')"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: data
